version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: simulador-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    env_file: 
      - ./.env 
